### ISSUE TITLE
efm-langserver install issues

### ISSUE THREAD

**Issue by ncunningham-stairsupplies** [e-cal/evim#3]
Im trying to get efm-langserver to work properly. I only installed with with `go get` but im still getting the error `False. Please check your path and ensure the server is installed`. Maybe i dont have `go` installed correctly? Any help would be great

**Comment by e-cal** [comment]
are you able to run `efm-langserver` on the command line? 
and can I see the output of `:LspInfo`?

**Comment by ncunningham-stairsupplies** [comment]
after looking into it further, on wsl2, you have to add a couple more environment variables for go to work properly. after fixing that efm-langserver worked properly
