### ISSUE TITLE
Installation missing a step regarding icons

### ISSUE THREAD

**Issue by vpzed** [e-cal/evim#5]
I'm new to customizing neovim/vim so I am following the posted installation steps, starting from a fresh neovim+pynvim install. 

When the posted installation steps are completed, the icons are not working like before Restore Session, Files, Find Text, etc. I looked at nvim-web-devicons and it mentions a patched font as a requirement. I looked into that but there are quite a few options, and I'm not sure which option is appropriate for Evim. 

Requesting the installation section be updated to include the steps required to obtain functioning icons.

Thank you!

![image](https://user-images.githubusercontent.com/30138020/162824395-48102201-91ec-44c2-b1fd-47e900036764.png)

**Comment by e-cal** [comment]
Any font from [here](https://www.nerdfonts.com/font-downloads) should work, then make sure you set whichever you download to your terminal font (likely just a line in your terminal's config file, should be in the docs for whichever you use, if you happen to use kitty here's [my config](https://github.com/e-cal/dotfiles/blob/b4be89c61bed21fbf235c9f319310c36ea683aad/global/dot-config/kitty/kitty.conf#L16)). 

Personally I like JetBrains Mono, but any nerd font will have all the symbols.
